// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4e5bWSsx1zrywjXxAQ_x9othCZ5Mk9Ow',
    appId: '1:105314225866:web:217cc40b726bac313d2e33',
    messagingSenderId: '105314225866',
    projectId: 'zoopzoop-2',
    authDomain: 'zoopzoop-2.firebaseapp.com',
    storageBucket: 'zoopzoop-2.appspot.com',
    measurementId: 'G-RE7V04C7X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMIXCp6fOsJhnYG8LF3sJ5DSMz1F8Vo_I',
    appId: '1:105314225866:android:3ed1fc0f56534dee3d2e33',
    messagingSenderId: '105314225866',
    projectId: 'zoopzoop-2',
    storageBucket: 'zoopzoop-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVgc-8aAoy5NnT0F63bUF7lK2jCpVbP_s',
    appId: '1:105314225866:ios:b939ed0020561df73d2e33',
    messagingSenderId: '105314225866',
    projectId: 'zoopzoop-2',
    storageBucket: 'zoopzoop-2.appspot.com',
    androidClientId: '105314225866-1pfi0nnt1ea15nlequk31sc7073908g1.apps.googleusercontent.com',
    iosClientId: '105314225866-ej8gd4kd5p6vk55mrmpbjh80srviivg1.apps.googleusercontent.com',
    iosBundleId: 'com.psuh.zoopzoop',
  );
}
